### ISSUE TITLE
Emoji 帮助库 如何在require环境使用?

### ISSUE THREAD

**Issue by wierli** [rongcloud/demo-web-sdk#6]
如题

require.config({
	paths: {
		handlebars: "lib/handlebars",
		jquery: "lib/jquery2.1",
		localResizeIMG: "lib/localResizeIMG",
		text: "lib/text",
		hbs: "lib/hbs",
		rongSDK: 'http://res.websdk.rongcloud.cn/RongIMClient-0.9.15.min',
		RongIM_IndexedDB:'http://res.websdk.rongcloud.cn/RongIMClient.indexedDB.min',
		RomgIM_Vioce: 'http://res.websdk.rongcloud.cn/RongIMClient.voice-0.9.1.min',
		RongIM_Emoji: 'http://res.websdk.rongcloud.cn/RongIMClient.emoji-0.9.2.min'
	},
	shim: {
		handlebars: {
			exports: "Handlebars",
		}
	}
});

define('app', ['js/router','js/welcomescreen','RongIM_Emoji','rongSDK'], function(Router,welcomescreen,RongIM_Emoji,RongIMClient) {
            RongIMClient.init(RongIM_APPKEY);

		var emojiObjectList = RongIMClient.Expression.getAllExpression(64,0);
	  //从下标为0的位置检索64个表情对象,startIndex与count只和最大为128，因为表情对象最多为128个。
	  for(var i=0,item;item=emojiObjectList[i++];){
	     console.log(item.englishName,item.chineseName,item.img,item.tag);
	     //依次打印表情元素
	  }
});

我使用的是谷歌浏览器
以下是报错日志
Uncaught Error: Please load RongIMClient.min.js,http://res.websdk.rong.io/RongIMClient.min.js(anonymous function) @ VM6115:1(anonymous function) @ VM6115:1(anonymous function) @ RongIMClient.emoji-0.9.2.min.js:1
app.js:72 Uncaught TypeError: Cannot read property 'getAllExpression' of undefined

请问如何正确的在require环境引用 顺便问一下voice 还有indexedDB 如何正确引用

**Comment by changxiaoqiang** [comment]
您好，请在融云站点发送工单解决此类问题
